import type { Metadata } from "next";
import Link from "next/link";

import { Bullets, PageTitle, Paragraph, Section } from "@/components/public/prose";
import { BRAND_NAME } from "@/lib/brand";
import { TERMS_VERSION } from "@/lib/terms";

export const metadata: Metadata = {
  title: "Terms",
  description: `The terms of using ${BRAND_NAME}: what it promises, what it does not, and what you agree to.`,
};

/**
 * `/terms` (terms ticket 01). Short and true rather than long and borrowed.
 *
 * There is no payment path in this product and a Plan is a row set by hand (ADR-0001), so the
 * commercial half of an ordinary terms page has nothing to describe and is not here. Neither is a
 * liability cap, a governing-law clause, or an arbitration clause: copying those from a template
 * nobody has read would make this page longer without making it truer.
 *
 * `/privacy` is where what is actually sent to which AI company is written down.
 */
export default function TermsPage() {
  return (
    <>
      <PageTitle version={TERMS_VERSION}>Terms</PageTitle>

      <Section id="what-this-is" heading="What this is">
        <Paragraph>
          {BRAND_NAME} is a job-application tracker for one person: your jobs, your contacts, your
          documents, and the writing this product does from them. These terms are between you and the
          person who makes it. They are short because there is not much to say, not because something
          has been left out.
        </Paragraph>
      </Section>

      <Section id="no-payment" heading="There is no payment">
        <Paragraph>
          Nothing here is bought. There is no card, no subscription, and no checkout, and no plan is
          sold — a plan is set by hand, and moving between plans never deletes anything you have.
          Nothing on this page is about money, because nothing about this product is.
        </Paragraph>
      </Section>

      <Section id="no-promises" heading="What is not promised">
        <Bullets
          items={[
            "No uptime or availability. This can be down, and can go away.",
            "No warranty of any kind. It is provided as it is.",
            "No guarantee that anything you keep here is backed up beyond the ordinary running of the service. Keep your own copies of documents that matter.",
          ]}
        />
      </Section>

      <Section id="ai" heading="What the AI writing is, and is not">
        <Paragraph>
          Cover letters, interview questions, interview scores, and your footing on a job are
          generated by AI, from what you gave this product. They can be wrong, out of date, or
          confidently plausible and untrue, and they are written to be edited rather than sent.
        </Paragraph>
        <Paragraph>
          None of it is career, legal, financial, or immigration advice, and none of it is a
          prediction about whether you will get a job. Read anything before you send it under your
          own name.{" "}
          <Link href="/privacy" className="underline underline-offset-4">
            The privacy page
          </Link>{" "}
          says exactly which text goes to which company.
        </Paragraph>
      </Section>

      <Section id="acceptable-use" heading="Acceptable use">
        <Paragraph>Do not use this product to:</Paragraph>
        <Bullets
          items={[
            "upload documents about someone else without their knowledge, or any material you have no right to hold",
            "attempt to reach another account’s data, or to probe the service for a way to",
            "put material into it in order to steer the AI into producing something harmful, or to test what it will refuse",
            "automate it at a volume a person could not produce, or resell what it generates as a service of your own",
          ]}
        />
        <Paragraph>
          Cover letters carry their own rule already: feedback that instructs the writer rather than
          describing the letter is flagged, and a second flag in one week pauses letter writing until
          the week ends. Nothing else about your account changes when that happens.
        </Paragraph>
        <Paragraph>
          Accounts doing any of the above can be ended without notice. That is the only sanction
          there is; there is nothing to refund.
        </Paragraph>
      </Section>

      <Section id="your-account" heading="Your account, and ending it">
        <Paragraph>
          You can delete your account from the account page at any time. Deletion is immediate and
          irreversible: every job, contact, document and its file, draft, quota week, plan, and record
          of these terms goes at once. There is no grace period and nothing to restore. App feedback
          you already sent is not recalled — it was never stored.
        </Paragraph>
      </Section>

      <Section id="changes" heading="Changes to these terms">
        <Paragraph>
          When what this product sends to which company changes, these terms change with it and you
          are asked to agree again the next time you sign in. The date at the top of this page is the
          version you are reading.
        </Paragraph>
      </Section>
    </>
  );
}
