// @vitest-environment node
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { INGEST_LIMITS, extractDocumentText, sniff } from "@/server/ingest/extract";

/** Real files of each kind, generated by `tests/fixtures/documents/generate.mjs`. */
const fixture = (name: string) =>
  new Uint8Array(readFileSync(join(process.cwd(), "tests", "fixtures", "documents", name)));

describe("extraction at upload (tickets 15, 19)", () => {
  it("ING-1: extracts the text of a PDF with a text layer", async () => {
    const result = await extractDocumentText(fixture("resume.pdf"), "pdf");

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.text).toContain("Sam Rivera - Senior Product Designer");
    expect(result.text).toContain("Skills: interaction design");
  });

  it("ING-1: extracts the text of a DOCX", async () => {
    const result = await extractDocumentText(fixture("resume.docx"), "docx");

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.text).toContain("Meridian Labs: led the redesign");
  });

  it("ING-2: detects a PDF with no text layer at upload, rather than storing empty text", async () => {
    expect(await extractDocumentText(fixture("scan.pdf"), "pdf")).toEqual({
      ok: false,
      reason: "no-text-layer",
    });
  });

  it("ING-3: recognises a password-protected PDF", async () => {
    expect(await extractDocumentText(fixture("locked.pdf"), "pdf")).toEqual({
      ok: false,
      reason: "password-protected",
    });
  });

  it("ING-3: recognises a password-protected DOCX by its container, not by mammoth's error", async () => {
    const bytes = fixture("locked.docx");
    expect(sniff(bytes)).toBe("cfb");
    expect(await extractDocumentText(bytes, "docx")).toEqual({
      ok: false,
      reason: "password-protected",
    });
  });

  it("ING-4: a file whose type contradicts its name is refused as a mismatch, both ways", async () => {
    expect(await extractDocumentText(fixture("pdf-named-as.docx"), "docx")).toEqual({
      ok: false,
      reason: "type-mismatch",
    });
    expect(await extractDocumentText(fixture("resume.docx"), "pdf")).toEqual({
      ok: false,
      reason: "type-mismatch",
    });
  });

  it("ING-5: garbage is unreadable, not a crash", async () => {
    const noise = new Uint8Array(4096).map((_, i) => (i * 131) % 251);
    expect(await extractDocumentText(noise, "pdf")).toEqual({ ok: false, reason: "unreadable" });
    expect(await extractDocumentText(noise, "docx")).toEqual({ ok: false, reason: "unreadable" });

    const truncated = fixture("resume.pdf").subarray(0, 200);
    expect((await extractDocumentText(truncated, "pdf")).ok).toBe(false);
  });

  it("ING-6: a PDF over the page cap is refused before its text is read", async () => {
    expect(INGEST_LIMITS.maxPdfPages).toBe(20);
    expect(await extractDocumentText(fixture("long.pdf"), "pdf")).toEqual({
      ok: false,
      reason: "too-many-pages",
    });
  });
});
