import type { Job } from "@/lib/jobs";

/**
 * The illustrative jobs the landing page draws its miniatures from. Marketing content, not data:
 * nothing here reaches an account, and the test fixtures (tests/fixtures/jobs.ts) are a separate copy
 * so the two can change independently (ticket 12).
 */
export const SAMPLE_JOBS: Job[] = [
  {
    id: "meridian-senior-product-designer",
    company: "Meridian Labs",
    role: "Senior Product Designer",
    location: "Remote (AU)",
    salaryMin: 150,
    salaryMax: 180,
    stage: "interested",
    postingUrl: "https://meridianlabs.example.com/careers/senior-product-designer",
    addedOn: "2026-07-22",
    appliedOn: null,
    resume: null,
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Meridian Labs is building measurement tooling for climate teams. We're looking for a Senior Product Designer to own the analytics surface end to end.",
    notes:
      "Referral from Priya — she can intro to the hiring manager once I've tailored the resume.",
    contacts: [],
    activity: [{ id: "a1", label: "Added to board — Interested", date: "2026-07-22" }],
    accent: "moss",
  },
  {
    id: "fernwood-product-designer-growth",
    company: "Fernwood",
    role: "Product Designer, Growth",
    location: "Hybrid · Brisbane",
    salaryMin: 125,
    salaryMax: 145,
    stage: "applied",
    postingUrl: "https://fernwood.example.com/jobs/product-designer-growth",
    addedOn: "2026-07-11",
    appliedOn: "2026-07-15",
    resume: { id: "seed-resume_growth_v2.pdf", fileName: "resume_growth_v2.pdf" },
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Fernwood is a subscription plant company. The Growth design team owns onboarding, pricing, and the referral loop.",
    notes: "Recruiter said they move fast — expect a screen within a week.",
    contacts: [
      {
        id: "c1",
        name: "Dana Whitfield",
        kind: "recruiter",
        title: "Recruiter",
        agency: "",
        email: "dana@fernwood.co",
        otherJobCount: 0,
      },
    ],
    activity: [
      {
        id: "a1",
        label: "Applied with resume_growth_v2.pdf",
        date: "2026-07-15",
      },
      { id: "a2", label: "Added to board — Interested", date: "2026-07-11" },
    ],
    accent: "forest",
  },
  {
    id: "cobalt-staff-ux-designer",
    company: "Cobalt Systems",
    role: "Staff UX Designer",
    location: "Remote (AU)",
    salaryMin: 170,
    salaryMax: 200,
    stage: "applied",
    postingUrl: "https://cobaltsystems.example.com/careers/staff-ux-designer",
    addedOn: "2026-07-02",
    appliedOn: "2026-07-09",
    resume: { id: "seed-resume_staff_v1.pdf", fileName: "resume_staff_v1.pdf" },
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Cobalt Systems sells infrastructure monitoring to platform teams. The Staff UX role leads design for the incident response product.",
    notes:
      "Heavy systems work — pull the design-system case study to the front of the portfolio.",
    contacts: [],
    activity: [
      { id: "a1", label: "Applied with resume_staff_v1.pdf", date: "2026-07-09" },
      { id: "a2", label: "Added to board — Interested", date: "2026-07-02" },
    ],
    accent: "teal",
  },
  {
    id: "harvest-lead-product-designer",
    company: "Harvest & Co",
    role: "Lead Product Designer",
    location: "Onsite · Melbourne",
    salaryMin: 140,
    salaryMax: 165,
    stage: "interviewing",
    postingUrl: "https://harvest.example.com/careers/lead-product-designer",
    addedOn: "2026-06-26",
    appliedOn: "2026-06-30",
    resume: { id: "seed-resume_lead_v1.pdf", fileName: "resume_lead_v1.pdf" },
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Harvest & Co is a food-tech company hiring a Lead Product Designer to build out our merchant experience.",
    notes:
      "Panel is 3 rounds: portfolio, cross-functional, exec. Prep case study on marketplace redesign.",
    contacts: [
      {
        id: "c1",
        name: "Tom Okafor",
        kind: "hiring_manager",
        title: "Design Manager",
        agency: "",
        email: "t.okafor@harvest.co",
        otherJobCount: 0,
      },
      {
        id: "c2",
        name: "Jess Liu",
        kind: "recruiter",
        title: "Recruiter",
        agency: "",
        email: "jess@harvest.co",
        otherJobCount: 0,
      },
    ],
    activity: [
      { id: "a1", label: "Portfolio review scheduled", date: "2026-07-20" },
      { id: "a2", label: "Moved to Interviewing", date: "2026-07-14" },
      { id: "a3", label: "Applied with resume_lead_v1.pdf", date: "2026-06-30" },
      { id: "a4", label: "Added to board — Interested", date: "2026-06-26" },
    ],
    accent: "wheat",
  },
  {
    id: "northbeam-product-designer-ii",
    company: "Northbeam",
    role: "Product Designer II",
    location: "Hybrid · Adelaide",
    salaryMin: null,
    salaryMax: null,
    stage: "interviewing",
    postingUrl: "https://northbeam.example.com/jobs/product-designer-ii",
    addedOn: "2026-06-28",
    appliedOn: "2026-07-04",
    resume: { id: "seed-resume_generalist_v3.pdf", fileName: "resume_generalist_v3.pdf" },
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Northbeam builds route planning for regional freight. This role sits on the dispatcher tools team.",
    notes: "No band posted. Ask the recruiter before the second round.",
    contacts: [
      {
        id: "c1",
        name: "Ravi Menon",
        kind: "hiring_manager",
        title: "Head of Design",
        agency: "",
        email: "ravi@northbeam.io",
        otherJobCount: 0,
      },
    ],
    activity: [
      { id: "a1", label: "Moved to Interviewing", date: "2026-07-18" },
      {
        id: "a2",
        label: "Applied with resume_generalist_v3.pdf",
        date: "2026-07-04",
      },
      { id: "a3", label: "Added to board — Interested", date: "2026-06-28" },
    ],
    accent: "olive",
  },
  {
    id: "bramble-senior-ux-designer",
    company: "Bramble",
    role: "Senior UX Designer",
    location: "Hybrid · Sydney",
    salaryMin: 145,
    salaryMax: 160,
    stage: "offer",
    postingUrl: "https://bramble.example.com/careers/senior-ux-designer",
    addedOn: "2026-06-08",
    appliedOn: "2026-06-14",
    resume: { id: "seed-resume_senior_v4.pdf", fileName: "resume_senior_v4.pdf" },
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Bramble is a family scheduling app. The Senior UX role owns the shared-calendar experience across web and mobile.",
    notes: "Offer verbal on 21 Jul. Written offer expected this week — compare against Harvest.",
    contacts: [
      {
        id: "c1",
        name: "Alex Chen",
        kind: "hiring_manager",
        title: "Design Director",
        agency: "",
        email: "alex@bramble.app",
        otherJobCount: 0,
      },
    ],
    activity: [
      { id: "a1", label: "Verbal offer received", date: "2026-07-21" },
      { id: "a2", label: "Final round complete", date: "2026-07-16" },
      { id: "a3", label: "Applied with resume_senior_v4.pdf", date: "2026-06-14" },
      { id: "a4", label: "Added to board — Interested", date: "2026-06-08" },
    ],
    accent: "slate",
  },
  {
    id: "quill-product-designer",
    company: "Quill Health",
    role: "Product Designer",
    location: "Remote (AU)",
    salaryMin: 130,
    salaryMax: 150,
    stage: "rejected",
    postingUrl: "https://quillhealth.example.com/jobs/product-designer",
    addedOn: "2026-06-19",
    appliedOn: "2026-06-24",
    resume: { id: "seed-resume_generalist_v3.pdf", fileName: "resume_generalist_v3.pdf" },
    coverLetter: null,
    draft: "",
    draftWrittenAt: null,
    description:
      "Quill Health builds intake software for small clinics. The role covers patient-facing forms and scheduling.",
    notes: "Passed after the screen — they wanted more healthcare domain depth.",
    contacts: [],
    activity: [
      { id: "a1", label: "Moved to Rejected", date: "2026-07-06" },
      {
        id: "a2",
        label: "Applied with resume_generalist_v3.pdf",
        date: "2026-06-24",
      },
      { id: "a3", label: "Added to board — Interested", date: "2026-06-19" },
    ],
    accent: "slate",
  },
];
